export const sizeThun = [
    {
        size: 0,
        caoMin: 155,
        caoMax: 159,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
    {
        size: 1,
        caoMin: 160,
        caoMax: 165,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
    {
        size: 2,
        caoMin: 166,
        caoMax: 172,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
    {
        size: 3,
        caoMin: 172,
        caoMax: 177,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
    {
        size: 4,
        caoMin: 177,
        caoMax: 183,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
];

export const sizeHoodie = [
    {
        size: 0,
        caoMin: 155,
        caoMax: 159,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
    {
        size: 1,
        caoMin: 160,
        caoMax: 165,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
    {
        size: 2,
        caoMin: 166,
        caoMax: 172,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
    {
        size: 3,
        caoMin: 172,
        caoMax: 177,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
    {
        size: 4,
        caoMin: 177,
        caoMax: 183,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
];

export const sizeSomi = [
    {
        size: 0,
        caoMin: 155,
        caoMax: 159,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
    {
        size: 1,
        caoMin: 160,
        caoMax: 165,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
    {
        size: 2,
        caoMin: 166,
        caoMax: 172,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
    {
        size: 3,
        caoMin: 172,
        caoMax: 177,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
    {
        size: 4,
        caoMin: 177,
        caoMax: 183,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
];

export const sizeJogger = [
    {
        size: 1,
        caoMin: 155,
        caoMax: 162,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
    {
        size: 2,
        caoMin: 163,
        caoMax: 169,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
    {
        size: 3,
        caoMin: 170,
        caoMax: 176,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
    {
        size: 4,
        caoMin: 177,
        caoMax: 183,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
];

export const sizeShort = [
    {
        size: 1,
        caoMin: 155,
        caoMax: 162,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
    {
        size: 2,
        caoMin: 163,
        caoMax: 169,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
    {
        size: 3,
        caoMin: 170,
        caoMax: 176,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
    {
        size: 4,
        caoMin: 177,
        caoMax: 182,
        nangMin: 48,
        nangMax: 84,
        type: [1, 2],
    },
];
