export const SET_PRODS = "SET_PRODS";
export const SET_PROD_DETAIL = "SET_PROD_DETAIL";
export const SET_CART = "SET_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_CART = "UPDATE_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SET_MYORDERS = "SET_MYORDER";
export const SET_AUTH = "SET_AUTH";
export const REMOVE_ORDER = "REMOVE_ORDER";

export const SET_PRODUCTS = "SET_PRODUCTS";
export const CHANGE_STATUS_PRODUCT = "CHANGE_STATUS_PRODUCT";
export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL";
export const ADD_PRODUCT = "ADD_PRODUCT";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const GET_ALL_CUSTOMER = "GET_ALL_CUSTOMER";
export const CREATE_CUSTOMER = "CREATE_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";

export const GET_PAGE_PRODUCT = "GET_PAGE_PRODUCT";

export const GET_CART_ITEM = "GET_CART_ITEM";
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";

export const CLEAR_CART = "CLEAR_CART";
